source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.0'
pod 'MJRefresh'
pod 'SDWebImage', '~> 3.7'
pod 'BaiduMapKit', '~> 2.10.0'
pod 'GTSDK'
pod 'RMUniversalAlert'

